import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { Language } from '../types';

type Translations = Record<string, string>;
type Dictionary = Record<Language, Translations>;

const dictionary: Dictionary = {
  'en': {
    'app.name': 'NostrLink',
    'app.desc': 'Secure, decentralized messaging.',
    'login.title': 'Login',
    'login.generate': 'Generate New Key',
    'login.or': 'Or',
    'login.placeholder': 'nsec1...',
    'login.error.format': 'Invalid key format. Must start with nsec.',
    'login.error.invalid': 'Invalid Private Key',
    'login.success': 'New Key Generated!',
    'login.warning': 'Save this key safely! If you lose it, your account is gone forever.',
    'nav.global': 'Global Chat',
    'nav.community': 'Community',
    'nav.group': 'Group Chat',
    'nav.dm': 'Direct Messages',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.relays': 'Relay Settings',
    'settings.add_relay': 'Add New Relay',
    'settings.connected': 'Connected Relays',
    'settings.health': 'Relay Health',
    'settings.health_desc': 'Lower latency (ms) means faster message delivery. We recommend keeping at least 2 green relays.',
    'settings.address': 'Your Address',
    'settings.copy': 'Copy',
    'settings.private_key': 'Private Key',
    'settings.private_key_warning': 'Store this private key safely. Anyone with it can control your account.',
    'settings.relay_invalid': 'Invalid relay URL.',
    'chat.placeholder': 'Broadcast to the world...',
    'chat.placeholder_dm': 'Send encrypted message...',
    'chat.connecting': 'Connecting to relays...',
    'chat.no_messages': 'No messages found.',
    'chat.be_first': 'Be the first to say hello!',
    'chat.send_failed': 'Failed to send. Check relay connection.',
    'dm.search': 'Start new chat (npub...)',
    'dm.no_convos': 'No conversations found.',
    'dm.start_prompt': 'Start a chat with a public key above.',
    'community.title': 'Community',
    'community.live': 'Live from',
    'community.listening': 'Listening for events...',
    'community.no_posts': 'No posts found on connected relays.',
    'community.post': 'Post',
    'community.posting': 'Posting...',
    'community.cancel': 'Cancel',
    'community.whats_happening': "What's happening?",
    'community.failed': 'Failed to post message.',
    'community.profile': 'Profile',
    'community.my_posts': 'My posts',
    'community.back': 'Back',
    'group.tab_public': 'Public',
    'group.tab_joined': 'Joined',
    'group.no_joined': 'No joined groups yet.',
    'group.channel_id': 'Channel ID:',
    'group.members': 'Members:',
    'group.info': 'Group Info',
    'group.close': 'Close',
    'group.name': 'Name',
    'group.about': 'About',
    'group.share': 'Share',
    'group.link_copied': 'Link copied',
    'community.me': 'You',
    'group.subtitle': 'Channels and group chats',
    'group.create': 'Create Group',
    'group.join': 'Join Group',
    'group.name_placeholder': 'Group name',
    'group.about_placeholder': 'About (optional)',
    'group.join_placeholder': 'Paste channel id...',
    'group.invalid_channel': 'Invalid channel id.',
    'group.create_failed': 'Failed to create group.',
    'group.no_channels': 'No groups found on connected relays.',
    'group.unknown_time': 'unknown',
    'group.unnamed': 'Untitled Group',
    'group.back': 'Back',
    'group.loading': 'Loading channel...',
    'group.no_messages': 'No messages found.',
    'group.be_first': 'Be the first to say hello!',
    'group.placeholder': 'Send a message to the group...',
    'group.send_failed': 'Failed to send. Check relay connection.',
  },
  'zh-CN': {
    'app.name': 'NostrLink',
    'app.desc': '安全、去中心化的消息传递。',
    'login.title': '登录',
    'login.generate': '生成新密钥',
    'login.or': '或',
    'login.placeholder': 'nsec1...',
    'login.error.format': '密钥格式无效，必须以 nsec 开头。',
    'login.error.invalid': '无效的私钥',
    'login.success': '新密钥已生成！',
    'login.warning': '请妥善保存此私钥！一旦丢失将无法找回。',
    'nav.global': '全球聊天',
    'nav.community': '社区',
    'nav.group': '群聊',
    'nav.dm': '私信',
    'nav.settings': '设置',
    'nav.logout': '退出登录',
    'settings.title': '设置',
    'settings.language': '语言',
    'settings.relays': '中继设置',
    'settings.add_relay': '添加新中继',
    'settings.connected': '已连接的中继',
    'settings.health': '中继健康',
    'settings.health_desc': '延迟(ms)越低，消息传递越快。建议至少保留 2 个健康中继。',
    'settings.address': '我的地址',
    'settings.copy': '复制',
    'settings.private_key': '私钥',
    'settings.private_key_warning': '请妥善保管私钥，任何人持有它都可控制你的账户。',
    'settings.relay_invalid': '中继地址无效。',
    'chat.placeholder': '向世界广播...',
    'chat.placeholder_dm': '发送加密消息...',
    'chat.connecting': '正在连接中继...',
    'chat.no_messages': '未找到消息。',
    'chat.be_first': '成为第一个打招呼的人！',
    'chat.send_failed': '发送失败，请检查中继连接。',
    'dm.search': '开始新聊天 (npub...)',
    'dm.no_convos': '未找到对话。',
    'dm.start_prompt': '使用上方的公钥开始聊天。',
    'community.title': '社区',
    'community.live': '实时来自',
    'community.listening': '正在监听事件...',
    'community.no_posts': '在已连接的中继中未找到帖子。',
    'community.post': '发布',
    'community.posting': '正在发布...',
    'community.cancel': '取消',
    'community.whats_happening': '发生了什么？',
    'community.failed': '发布失败。',
    'community.profile': '个人主页',
    'community.my_posts': '我的帖子',
    'community.back': '返回',
    'group.tab_public': '????',
    'group.tab_joined': '??????',
    'group.no_joined': '??? ?????, ? ??????? ?? ????????.',
    'group.channel_id': '??ID?',
    'group.members': '????',
    'group.info': '????',
    'group.close': '??',
    'group.name': '??',
    'group.about': '??',
    'group.share': '??',
    'group.link_copied': '?????',
    'community.me': '我',
    'group.subtitle': '群组与频道聊天',
    'group.create': '创建群聊',
    'group.join': '加入群聊',
    'group.name_placeholder': '群聊名称',
    'group.about_placeholder': '群聊简介（可选）',
    'group.join_placeholder': '粘贴群聊ID...',
    'group.invalid_channel': '群聊ID无效。',
    'group.create_failed': '创建群聊失败。',
    'group.no_channels': '在已连接的中继中未找到群聊。',
    'group.unknown_time': '未知',
    'group.unnamed': '未命名群聊',
    'group.back': '返回',
    'group.loading': '正在加载群聊...',
    'group.no_messages': '暂无消息。',
    'group.be_first': '成为第一个发言的人！',
    'group.placeholder': '发送群聊消息...',
    'group.send_failed': '发送失败，请检查中继连接。',
  },
  'zh-TW': {
    'app.name': 'NostrLink',
    'app.desc': '安全、去中心化的訊息傳遞。',
    'login.title': '登入',
    'login.generate': '產生新金鑰',
    'login.or': '或',
    'login.placeholder': 'nsec1...',
    'login.error.format': '金鑰格式無效，必須以 nsec 開頭。',
    'login.error.invalid': '無效的私鑰',
    'login.success': '新金鑰已產生！',
    'login.warning': '請妥善保存私鑰！遺失將無法找回。',
    'nav.global': '全球聊天',
    'nav.community': '社群',
    'nav.group': '群聊',
    'nav.dm': '私訊',
    'nav.settings': '設定',
    'nav.logout': '登出',
    'settings.title': '設定',
    'settings.language': '語言',
    'settings.relays': '中繼設定',
    'settings.add_relay': '新增中繼',
    'settings.connected': '已連線的中繼',
    'settings.health': '中繼健康',
    'settings.health_desc': '延遲(ms)越低，訊息傳遞越快。建議至少保留 2 個健康中繼。',
    'settings.address': '我的地址',
    'settings.copy': '複製',
    'settings.private_key': '私鑰',
    'settings.private_key_warning': '請妥善保管私鑰，任何人持有它都可控制你的帳戶。',
    'settings.relay_invalid': '中繼地址無效。',
    'chat.placeholder': '向世界廣播...',
    'chat.placeholder_dm': '傳送加密訊息...',
    'chat.connecting': '正在連線中繼...',
    'chat.no_messages': '未找到訊息。',
    'chat.be_first': '成為第一個打招呼的人！',
    'chat.send_failed': '傳送失敗，請檢查中繼連線。',
    'dm.search': '開始新聊天 (npub...)',
    'dm.no_convos': '未找到對話。',
    'dm.start_prompt': '使用上方的公鑰開始聊天。',
    'community.title': '社群',
    'community.live': '即時來自',
    'community.listening': '正在監聽事件...',
    'community.no_posts': '在已連線的中繼中未找到貼文。',
    'community.post': '發布',
    'community.posting': '正在發布...',
    'community.cancel': '取消',
    'community.whats_happening': '發生了什麼？',
    'community.failed': '發布失敗。',
    'community.profile': '個人頁面',
    'community.my_posts': '我的貼文',
    'community.back': '返回',
    'group.tab_public': '????',
    'group.tab_joined': '??????',
    'group.no_joined': '??? ?????, ? ??????? ?? ????????.',
    'group.channel_id': '??ID?',
    'group.members': '????',
    'group.info': '????',
    'group.close': '??',
    'group.name': '??',
    'group.about': '??',
    'group.share': '??',
    'group.link_copied': '?????',
    'community.me': '我',
    'group.subtitle': '群組與頻道聊天',
    'group.create': '建立群聊',
    'group.join': '加入群聊',
    'group.name_placeholder': '群聊名稱',
    'group.about_placeholder': '群聊簡介（選填）',
    'group.join_placeholder': '貼上群聊ID...',
    'group.invalid_channel': '群聊ID無效。',
    'group.create_failed': '建立群聊失敗。',
    'group.no_channels': '在已連線的中繼中未找到群聊。',
    'group.unknown_time': '未知',
    'group.unnamed': '未命名群聊',
    'group.back': '返回',
    'group.loading': '正在載入群聊...',
    'group.no_messages': '暫無訊息。',
    'group.be_first': '成為第一個發言的人！',
    'group.placeholder': '傳送群聊訊息...',
    'group.send_failed': '傳送失敗，請檢查中繼連線。',
  },
  'ru': {
    'app.name': 'NostrLink',
    'app.desc': 'Безопасные децентрализованные сообщения.',
    'login.title': 'Вход',
    'login.generate': 'Создать новый ключ',
    'login.or': 'Или',
    'login.placeholder': 'nsec1...',
    'login.error.format': 'Неверный формат ключа. Должен начинаться с nsec.',
    'login.error.invalid': 'Недействительный приватный ключ',
    'login.success': 'Новый ключ создан!',
    'login.warning': 'Сохраните ключ! Если вы его потеряете, аккаунт будет утерян навсегда.',
    'nav.global': 'Глобальный чат',
    'nav.community': 'Сообщество',
    'nav.group': 'Групповой чат',
    'nav.dm': 'Личные сообщения',
    'nav.settings': 'Настройки',
    'nav.logout': 'Выйти',
    'settings.title': 'Настройки',
    'settings.language': 'Язык',
    'settings.relays': 'Настройки реле',
    'settings.add_relay': 'Добавить реле',
    'settings.connected': 'Подключенные реле',
    'settings.health': 'Состояние реле',
    'settings.health_desc': 'Чем ниже задержка (мс), тем быстрее доставка. Рекомендуем минимум 2 здоровых реле.',
    'settings.address': 'Мой адрес',
    'settings.copy': 'Копировать',
    'settings.private_key': 'Приватный ключ',
    'settings.private_key_warning': 'Храните приватный ключ в безопасности. Любой, у кого он есть, может управлять аккаунтом.',
    'settings.relay_invalid': 'Неверный адрес реле.',
    'chat.placeholder': 'Сообщение всему миру...',
    'chat.placeholder_dm': 'Отправить зашифрованное сообщение...',
    'chat.connecting': 'Подключение к реле...',
    'chat.no_messages': 'Сообщения не найдены.',
    'chat.be_first': 'Скажите привет первым!',
    'chat.send_failed': 'Не удалось отправить. Проверьте подключение к реле.',
    'dm.search': 'Начать новый чат (npub...)',
    'dm.no_convos': 'Диалоги не найдены.',
    'dm.start_prompt': 'Начните чат с публичным ключом выше.',
    'community.title': 'Сообщество',
    'community.live': 'Прямой эфир с',
    'community.listening': 'Ожидание событий...',
    'community.no_posts': 'Посты не найдены на подключенных реле.',
    'community.post': 'Опубликовать',
    'community.posting': 'Публикация...',
    'community.cancel': 'Отмена',
    'community.whats_happening': 'Что происходит?',
    'community.failed': 'Не удалось опубликовать сообщение.',
    'community.profile': 'Профиль',
    'community.my_posts': 'Мои посты',
    'community.back': 'Назад',
    'group.tab_public': '?????????',
    'group.tab_joined': '??? ??????',
    'group.no_joined': '??? ?????, ? ??????? ?? ????????.',
    'group.channel_id': 'ID ??????:',
    'group.members': '?????????:',
    'group.info': '???? ? ??????',
    'group.close': '???????',
    'group.name': '????????',
    'group.about': '????????',
    'group.share': '??????????',
    'group.link_copied': '?????? ???????????',
    'community.me': 'Я',
    'group.subtitle': 'Каналы и групповые чаты',
    'group.create': 'Создать группу',
    'group.join': 'Войти в группу',
    'group.name_placeholder': 'Название группы',
    'group.about_placeholder': 'Описание (необязательно)',
    'group.join_placeholder': 'Вставьте id канала...',
    'group.invalid_channel': 'Неверный id канала.',
    'group.create_failed': 'Не удалось создать группу.',
    'group.no_channels': 'Группы не найдены на подключенных реле.',
    'group.unknown_time': 'неизвестно',
    'group.unnamed': 'Без названия',
    'group.back': 'Назад',
    'group.loading': 'Загрузка канала...',
    'group.no_messages': 'Сообщения не найдены.',
    'group.be_first': 'Скажите привет первым!',
    'group.placeholder': 'Отправить сообщение в группу...',
    'group.send_failed': 'Не удалось отправить. Проверьте подключение к реле.',
  },
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('nostr_lang') as Language;
    if (saved && dictionary[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('nostr_lang', lang);
  };

  const t = (key: string): string => {
    return dictionary[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
